name: xorhift
description: Pseudorandom number generator using xorshift128+
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # :)

dev_dependencies:
  test: ^1.5.1



