name: xrandom
description: "All-purpose, rock-solid random number generators focused on
              the reproducibility of tests on different platforms"
version: 0.2.0
homepage: https://github.com/rtmigo/xrandom

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # :)

dev_dependencies:
  quiver: ^3.0.0
  test: ^1.5.1