name: xrandom
description: "All-purpose, rock-solid random number generators
              focused on the consistency and reproducibility"
version: 0.5.0
homepage: https://github.com/rtmigo/xrandom

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  quiver: ^3.0.0
  test: ^1.5.1