name: xrandom
description: "Fast random number generators: xorshift32, xorshift64, xorshift128 and xorshift128+"
version: 0.0.2
homepage: https://github.com/rtmigo/xrandom

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # :)

dev_dependencies:
  test: ^1.5.1